PK_LOCATIONS = [
    # Major cities
    {
        "name": "Islamabad",
        "alternate_names": ["ISB", "Islaamabad"],
        "type": "city",
        "city": "Islamabad",
        "district": "Islamabad Capital Territory",
        "province": "Islamabad Capital Territory",
        "latitude": 33.6844,
        "longitude": 73.0479,
    },
    {
        "name": "Rawalpindi",
        "alternate_names": ["Pindi", "RWP"],
        "type": "city",
        "city": "Rawalpindi",
        "district": "Rawalpindi",
        "province": "Punjab",
        "latitude": 33.5651,
        "longitude": 73.0169,
    },
    {
        "name": "Lahore",
        "alternate_names": ["LHR", "Lahur"],
        "type": "city",
        "city": "Lahore",
        "district": "Lahore",
        "province": "Punjab",
        "latitude": 31.5204,
        "longitude": 74.3587,
    },
    {
        "name": "Karachi",
        "alternate_names": ["KHI", "Karaci"],
        "type": "city",
        "city": "Karachi",
        "district": "Karachi",
        "province": "Sindh",
        "latitude": 24.8607,
        "longitude": 67.0011,
    },
    {
        "name": "Peshawar",
        "alternate_names": ["Peshawr", "PSW"],
        "type": "city",
        "city": "Peshawar",
        "district": "Peshawar",
        "province": "Khyber Pakhtunkhwa",
        "latitude": 34.0151,
        "longitude": 71.5249,
    },
    {
        "name": "Quetta",
        "alternate_names": ["QTA", "Kwatta"],
        "type": "city",
        "city": "Quetta",
        "district": "Quetta",
        "province": "Balochistan",
        "latitude": 30.1798,
        "longitude": 66.9750,
    },
    {
        "name": "Multan",
        "alternate_names": ["MUX", "Mooltan"],
        "type": "city",
        "city": "Multan",
        "district": "Multan",
        "province": "Punjab",
        "latitude": 30.1575,
        "longitude": 71.5249,
    },
    {
        "name": "Faisalabad",
        "alternate_names": ["FSD", "Lyallpur"],
        "type": "city",
        "city": "Faisalabad",
        "district": "Faisalabad",
        "province": "Punjab",
        "latitude": 31.4504,
        "longitude": 73.1350,
    },
    {
        "name": "Hyderabad",
        "alternate_names": ["HYD"],
        "type": "city",
        "city": "Hyderabad",
        "district": "Hyderabad",
        "province": "Sindh",
        "latitude": 25.3960,
        "longitude": 68.3578,
    },
    {
        "name": "Sialkot",
        "alternate_names": ["SKT"],
        "type": "city",
        "city": "Sialkot",
        "district": "Sialkot",
        "province": "Punjab",
        "latitude": 32.4945,
        "longitude": 74.5229,
    },
    {
        "name": "Gujranwala",
        "alternate_names": ["GRW"],
        "type": "city",
        "city": "Gujranwala",
        "district": "Gujranwala",
        "province": "Punjab",
        "latitude": 32.1877,
        "longitude": 74.1945,
    },
    {
        "name": "Murree",
        "alternate_names": ["Mari"],
        "type": "city",
        "city": "Murree",
        "district": "Rawalpindi",
        "province": "Punjab",
        "latitude": 33.9070,
        "longitude": 73.3943,
    },
    {
        "name": "Gwadar",
        "alternate_names": ["Gawadar"],
        "type": "city",
        "city": "Gwadar",
        "district": "Gwadar",
        "province": "Balochistan",
        "latitude": 25.1264,
        "longitude": 62.3225,
    },
    {
        "name": "Sukkur",
        "alternate_names": ["Sakhar"],
        "type": "city",
        "city": "Sukkur",
        "district": "Sukkur",
        "province": "Sindh",
        "latitude": 27.7052,
        "longitude": 68.8574,
    },
    {
        "name": "Bahawalpur",
        "alternate_names": ["BWP"],
        "type": "city",
        "city": "Bahawalpur",
        "district": "Bahawalpur",
        "province": "Punjab",
        "latitude": 29.3956,
        "longitude": 71.6836,
    },
    # Landmarks / specific locations
    {
        "name": "D-Chowk",
        "alternate_names": ["D Chowk", "D-chowk", "Democracy Chowk"],
        "type": "landmark",
        "city": "Islamabad",
        "district": "Islamabad Capital Territory",
        "province": "Islamabad Capital Territory",
        "latitude": 33.7077,
        "longitude": 73.0498,
    },
    {
        "name": "Faizabad",
        "alternate_names": ["Faizabad Interchange", "Faizabad Islamabad"],
        "type": "landmark",
        "city": "Islamabad",
        "district": "Islamabad Capital Territory",
        "province": "Islamabad Capital Territory",
        "latitude": 33.6601,
        "longitude": 73.0637,
    },
    {
        "name": "Saddar Rawalpindi",
        "alternate_names": ["Saddar RWP", "Saddar Pindi"],
        "type": "area",
        "city": "Rawalpindi",
        "district": "Rawalpindi",
        "province": "Punjab",
        "latitude": 33.5960,
        "longitude": 73.0492,
    },
    {
        "name": "Saddar Karachi",
        "alternate_names": ["Saddar KHI", "Saddar Town"],
        "type": "area",
        "city": "Karachi",
        "district": "Karachi South",
        "province": "Sindh",
        "latitude": 24.8556,
        "longitude": 67.0280,
    },
    {
        "name": "Murree Road",
        "alternate_names": ["Murree Rd"],
        "type": "road",
        "city": "Rawalpindi",
        "district": "Rawalpindi",
        "province": "Punjab",
        "latitude": 33.5870,
        "longitude": 73.0551,
    },
    {
        "name": "Mall Road Lahore",
        "alternate_names": ["Mall Road", "The Mall Lahore"],
        "type": "road",
        "city": "Lahore",
        "district": "Lahore",
        "province": "Punjab",
        "latitude": 31.5580,
        "longitude": 74.3239,
    },
    {
        "name": "Liberty Chowk",
        "alternate_names": ["Liberty", "Liberty Market", "Liberty Roundabout"],
        "type": "landmark",
        "city": "Lahore",
        "district": "Lahore",
        "province": "Punjab",
        "latitude": 31.5117,
        "longitude": 74.3416,
    },
    {
        "name": "Shahrah-e-Faisal",
        "alternate_names": ["Sharah e Faisal", "Shahrah Faisal", "SE Faisal"],
        "type": "road",
        "city": "Karachi",
        "district": "Karachi East",
        "province": "Sindh",
        "latitude": 24.8660,
        "longitude": 67.0645,
    },
    {
        "name": "University Road Karachi",
        "alternate_names": ["University Road", "Uni Road KHI"],
        "type": "road",
        "city": "Karachi",
        "district": "Karachi East",
        "province": "Sindh",
        "latitude": 24.9280,
        "longitude": 67.0780,
    },
    {
        "name": "Blue Area",
        "alternate_names": ["Blue Area Islamabad", "Jinnah Avenue"],
        "type": "area",
        "city": "Islamabad",
        "district": "Islamabad Capital Territory",
        "province": "Islamabad Capital Territory",
        "latitude": 33.7100,
        "longitude": 73.0551,
    },
    {
        "name": "G-9 Markaz",
        "alternate_names": ["G9 Markaz", "G-9"],
        "type": "area",
        "city": "Islamabad",
        "district": "Islamabad Capital Territory",
        "province": "Islamabad Capital Territory",
        "latitude": 33.6910,
        "longitude": 73.0300,
    },
    {
        "name": "Zero Point Islamabad",
        "alternate_names": ["Zero Point", "Faisal Chowk"],
        "type": "landmark",
        "city": "Islamabad",
        "district": "Islamabad Capital Territory",
        "province": "Islamabad Capital Territory",
        "latitude": 33.6938,
        "longitude": 73.0652,
    },
    {
        "name": "Torkham",
        "alternate_names": ["Torkham Border", "Torkham Gate"],
        "type": "border_crossing",
        "city": "Torkham",
        "district": "Khyber",
        "province": "Khyber Pakhtunkhwa",
        "latitude": 34.0958,
        "longitude": 71.0931,
    },
    {
        "name": "Chaman",
        "alternate_names": ["Chaman Border"],
        "type": "border_crossing",
        "city": "Chaman",
        "district": "Killa Abdullah",
        "province": "Balochistan",
        "latitude": 30.9210,
        "longitude": 66.4597,
    },
    {
        "name": "Clifton Karachi",
        "alternate_names": ["Clifton", "Sea View"],
        "type": "area",
        "city": "Karachi",
        "district": "Karachi South",
        "province": "Sindh",
        "latitude": 24.8138,
        "longitude": 67.0300,
    },
]
